version: '3.8'
services:
  patricia:
    extends:
      file: docker.config.yml
      service: patricia
    build:
        context: ./
        dockerfile: Dockerfile
    # command: ["tail", "-f", "/dev/null"]
    command: ["node", "src/main.js"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9877:9877"
      # For nodemon during local developments
      - "9878:9878"

  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"
  mq:
    image: rabbitmq:3.6.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: none
 
