version: '3.8'
services:
  # patricia:
  #   extends:
  #     file: config.yml
  #     service: patricia
  #   build:
  #       context: ./
  #       dockerfile: Dockerfile.dev
  #   # command: ["bash", "-c", "npm run start:dev"]
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "8088:8088"
  #     # For nodemon during local developments
  #     - "9878:9878"

  redis:
    image: redis:6.2.4
    ports:
      - "6379:6379"
  mq:
    image: rabbitmq:3.6.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: none
 
