version: 2.1
orbs:
  docker: circleci/docker@2.1.2

jobs:
  test:
    docker:
      - image: node:14.17.0-buster
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: apt-get -qq update && apt-get install libc6-dev=2.28-10 && apt-get -qq
            install -y libboost-all-dev=1.67.0.1 libsodium-dev=1.0.17-1
            libsodium23=1.0.17-1
      - run:
          name: Install dependencies
          command: npm install
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - master
                - develop
      - docker/publish:
          requires:
            - test
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          filters:
            branches:
              only:
                - main
                - master
                - develop
