version: 2.1
orbs:
  docker: circleci/docker@2.0.1

jobs:
  test:
    docker:
      - image: node:14.17.0-buster
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: apt-get -qq update && apt-get install libc6-dev=2.28-10 && apt-get -qq
            install -y libboost-all-dev=1.67.0.1 libsodium-dev=1.0.17-1
            libsodium23=1.0.17-1
      - run:
          name: Install dependencies
          command: npm install



workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - master
                - develop
      
      - docker/publish:
          requires:
            - test
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
          # extra_build_args: '--platform linux/amd64'
          filters:
            branches:
              only:
                - main
                - master
                - develop


