// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: src/patricia.proto

package patricia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockStatus int32

const (
	BlockStatus_INVALID BlockStatus = 0
	BlockStatus_VALID   BlockStatus = 1
	BlockStatus_WINNER  BlockStatus = 2
)

// Enum value maps for BlockStatus.
var (
	BlockStatus_name = map[int32]string{
		0: "INVALID",
		1: "VALID",
		2: "WINNER",
	}
	BlockStatus_value = map[string]int32{
		"INVALID": 0,
		"VALID":   1,
		"WINNER":  2,
	}
)

func (x BlockStatus) Enum() *BlockStatus {
	p := new(BlockStatus)
	*p = x
	return p
}

func (x BlockStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlockStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_patricia_proto_enumTypes[0].Descriptor()
}

func (BlockStatus) Type() protoreflect.EnumType {
	return &file_src_patricia_proto_enumTypes[0]
}

func (x BlockStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlockStatus.Descriptor instead.
func (BlockStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_patricia_proto_rawDescGZIP(), []int{0}
}

// A constructed block (hex_blob+nonces+seed_hash) should equal hex_result
type PatriciaBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HexBlob    string `protobuf:"bytes,1,opt,name=hex_blob,json=hexBlob,proto3" json:"hex_blob,omitempty"`
	HexNonce   string `protobuf:"bytes,2,opt,name=hex_nonce,json=hexNonce,proto3" json:"hex_nonce,omitempty"`
	ExtraNonce uint32 `protobuf:"varint,3,opt,name=extra_nonce,json=extraNonce,proto3" json:"extra_nonce,omitempty"`
	SeedHash   string `protobuf:"bytes,4,opt,name=seed_hash,json=seedHash,proto3" json:"seed_hash,omitempty"`
	// Consider this a "checksum"
	HexResult string `protobuf:"bytes,5,opt,name=hex_result,json=hexResult,proto3" json:"hex_result,omitempty"`
	// Really a 256bit int
	LocalDiff  string `protobuf:"bytes,6,opt,name=local_diff,json=localDiff,proto3" json:"local_diff,omitempty"`
	GlobalDiff string `protobuf:"bytes,7,opt,name=global_diff,json=globalDiff,proto3" json:"global_diff,omitempty"`
}

func (x *PatriciaBlock) Reset() {
	*x = PatriciaBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_patricia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatriciaBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatriciaBlock) ProtoMessage() {}

func (x *PatriciaBlock) ProtoReflect() protoreflect.Message {
	mi := &file_src_patricia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatriciaBlock.ProtoReflect.Descriptor instead.
func (*PatriciaBlock) Descriptor() ([]byte, []int) {
	return file_src_patricia_proto_rawDescGZIP(), []int{0}
}

func (x *PatriciaBlock) GetHexBlob() string {
	if x != nil {
		return x.HexBlob
	}
	return ""
}

func (x *PatriciaBlock) GetHexNonce() string {
	if x != nil {
		return x.HexNonce
	}
	return ""
}

func (x *PatriciaBlock) GetExtraNonce() uint32 {
	if x != nil {
		return x.ExtraNonce
	}
	return 0
}

func (x *PatriciaBlock) GetSeedHash() string {
	if x != nil {
		return x.SeedHash
	}
	return ""
}

func (x *PatriciaBlock) GetHexResult() string {
	if x != nil {
		return x.HexResult
	}
	return ""
}

func (x *PatriciaBlock) GetLocalDiff() string {
	if x != nil {
		return x.LocalDiff
	}
	return ""
}

func (x *PatriciaBlock) GetGlobalDiff() string {
	if x != nil {
		return x.GlobalDiff
	}
	return ""
}

type PatriciaBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockStatus BlockStatus `protobuf:"varint,1,opt,name=block_status,json=blockStatus,proto3,enum=patricia.BlockStatus" json:"block_status,omitempty"`
	Test        string      `protobuf:"bytes,2,opt,name=test,proto3" json:"test,omitempty"`
}

func (x *PatriciaBlockResponse) Reset() {
	*x = PatriciaBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_patricia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatriciaBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatriciaBlockResponse) ProtoMessage() {}

func (x *PatriciaBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_patricia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatriciaBlockResponse.ProtoReflect.Descriptor instead.
func (*PatriciaBlockResponse) Descriptor() ([]byte, []int) {
	return file_src_patricia_proto_rawDescGZIP(), []int{1}
}

func (x *PatriciaBlockResponse) GetBlockStatus() BlockStatus {
	if x != nil {
		return x.BlockStatus
	}
	return BlockStatus_INVALID
}

func (x *PatriciaBlockResponse) GetTest() string {
	if x != nil {
		return x.Test
	}
	return ""
}

var File_src_patricia_proto protoreflect.FileDescriptor

var file_src_patricia_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x22, 0xe4,
	0x01, 0x0a, 0x0d, 0x50, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x19, 0x0a, 0x08, 0x68, 0x65, 0x78, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x78, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x1b, 0x0a, 0x09, 0x68,
	0x65, 0x78, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x68, 0x65, 0x78, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x65,
	0x64, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65,
	0x65, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x65, 0x78, 0x5f, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x65, 0x78, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x64,
	0x69, 0x66, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x44, 0x69, 0x66, 0x66, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x64,
	0x69, 0x66, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x44, 0x69, 0x66, 0x66, 0x22, 0x65, 0x0a, 0x15, 0x50, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69,
	0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x2a, 0x31, 0x0a, 0x0b,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x10, 0x02, 0x32,
	0x56, 0x0a, 0x08, 0x50, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x12, 0x4a, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x17, 0x2e, 0x70, 0x61,
	0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x2e, 0x50, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x1f, 0x2e, 0x70, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x2e,
	0x50, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x79, 0x72, 0x69, 0x61, 0x64, 0x65, 0x69, 0x6e, 0x63,
	0x2f, 0x70, 0x61, 0x74, 0x72, 0x69, 0x63, 0x69, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_src_patricia_proto_rawDescOnce sync.Once
	file_src_patricia_proto_rawDescData = file_src_patricia_proto_rawDesc
)

func file_src_patricia_proto_rawDescGZIP() []byte {
	file_src_patricia_proto_rawDescOnce.Do(func() {
		file_src_patricia_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_patricia_proto_rawDescData)
	})
	return file_src_patricia_proto_rawDescData
}

var file_src_patricia_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_patricia_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_patricia_proto_goTypes = []interface{}{
	(BlockStatus)(0),              // 0: patricia.BlockStatus
	(*PatriciaBlock)(nil),         // 1: patricia.PatriciaBlock
	(*PatriciaBlockResponse)(nil), // 2: patricia.PatriciaBlockResponse
}
var file_src_patricia_proto_depIdxs = []int32{
	0, // 0: patricia.PatriciaBlockResponse.block_status:type_name -> patricia.BlockStatus
	1, // 1: patricia.Patricia.processBlock:input_type -> patricia.PatriciaBlock
	2, // 2: patricia.Patricia.processBlock:output_type -> patricia.PatriciaBlockResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_patricia_proto_init() }
func file_src_patricia_proto_init() {
	if File_src_patricia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_patricia_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatriciaBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_patricia_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatriciaBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_patricia_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_patricia_proto_goTypes,
		DependencyIndexes: file_src_patricia_proto_depIdxs,
		EnumInfos:         file_src_patricia_proto_enumTypes,
		MessageInfos:      file_src_patricia_proto_msgTypes,
	}.Build()
	File_src_patricia_proto = out.File
	file_src_patricia_proto_rawDesc = nil
	file_src_patricia_proto_goTypes = nil
	file_src_patricia_proto_depIdxs = nil
}
